[env:m5stack-basic]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
board_build.filesystem = spiffs
monitor_speed = 115200
upload_port = COM9
upload_speed = 115200
lib_deps =
  m5stack/M5Stack
  links2004/WebSockets
build_flags =
  -DCORE_DEBUG_LEVEL=0

[env:m5stick-s3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_port = COM10
lib_deps =
  m5stack/M5Unified
  links2004/WebSockets
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DM5STICK_S3_TARGET
